### PR TITLE
Add semicolon syntax and int data type

### PR DESCRIPTION
**Pull request by durgeshra**
This change is [Reviewable](https://reviewable.io/reviews/cimulator/cimulator/16)

### CODE REVIEW

**Review by cimulator — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cimulator/cimulator/16)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @durgeshra)

___
*[lexer.go, line 31 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuvY_ZBtAIVYDPijh8:-LPuvY_ZBtAIVYDPijh9:b193zde) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L31)):*
> ```Go
> func init() {
> 	Regex[NUM] = regexp.MustCompile(`^[0-9][0-9\.eE]*`)
> 	Regex[VARNAME] = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9_]*`)
> ```

Just use VAR instead of VARNAME

https://github.com/golang/go/wiki/CodeReviewComments#variable-names
___
*[lexer.go, line 32 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuvyha1WqgBPoH97LF:-LPuvyha1WqgBPoH97LG:b-nkhsfw) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L32)):*
> ```
> Regex[DATATYPE] = regexp.MustCompile(`^int`)
> ```
This is not needed
___
*[lexer.go, line 67 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuw7o0DgDdow-ScfS6:-LPuw7o0DgDdow-ScfS7:bb4xgaa) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L67)):*
> ```
> v := x.fromRegex(DATATYPE, yylval, 0)
> ```
Don't use DATATYPE, just use VAR (since VAR is a superset).
Then check if the name is a reserved keyword (in this case, int); Use InSlice to check among multiple keywords/datatypes maybe?
___
*[lexer.go, line 80 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuteXx7kHSW24IhG3Z:-LPuteXx7kHSW24IhG3_:b7bijnh) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L80)):*
>```
>, 1)
>```

What is this new flag? Add a comment explaining it.
___
*[parse.go.y, line 67 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPut_w-DaTkaIC-wM5J:-LPut_w-DaTkaIC-wM5K:bhmnzo1) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/parse.go.y#L67)):*
> ```Yacc
> %%
> 
> //isDeclared checks if variable has been declared or not
> ```

comments should start with a space

**Review by durgeshra — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cimulator/cimulator/16)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @durgeshra)

___
*[lexer.go, line 31 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuvY_ZBtAIVYDPijh8:-LPuykG5-URIEQK0Cn4P:bd50szn) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L31)):*
<details><summary><i>Previously, cimulator wrote…</i></summary><blockquote>

Just use VAR instead of VARNAME

https://github.com/golang/go/wiki/CodeReviewComments#variable-names
</blockquote></details>

I thought of maintaining uniformity with the varname inside struct (I cannot use var there since it is reserved). Is it okay or it should be changed?
___
*[lexer.go, line 32 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuvyha1WqgBPoH97LF:-LPuzEgHEin9FFWQfNXr:b-lzw3qu) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L32)):*
<details><summary><i>Previously, cimulator wrote…</i></summary><blockquote>

> ```
> Regex[DATATYPE] = regexp.MustCompile(`^int`)
> ```
This is not needed
</blockquote></details>

I thought that might be needed when we extend this to float, long, etc.

**Review by cimulator — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cimulator/cimulator/16)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @durgeshra and @cimulator)

___
*[lexer.go, line 31 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuvY_ZBtAIVYDPijh8:-LPv-D3s0SGYhEA0IjBS:b-f0eplz) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L31)):*
<details><summary><i>Previously, durgeshra (Durgesh Agrawal) wrote…</i></summary><blockquote>

I thought of maintaining uniformity with the varname inside struct (I cannot use var there since it is reserved). Is it okay or it should be changed?
</blockquote></details>

Got it. This is fine then
___
*[lexer.go, line 32 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuvyha1WqgBPoH97LF:-LPv-HPl4Yx-D1o429Ck:blbs9fx) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L32)):*
<details><summary><i>Previously, durgeshra (Durgesh Agrawal) wrote…</i></summary><blockquote>

I thought that might be needed when we extend this to float, long, etc.
</blockquote></details>

No, won't be. Read my comment where this is used.

**Review by durgeshra — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cimulator/cimulator/16)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @cimulator and @durgeshra)

___
*[lexer.go, line 67 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuw7o0DgDdow-ScfS6:-LPvGZz09gVBpVCmhvJR:b-797bn) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L67)):*
<details><summary><i>Previously, cimulator wrote…</i></summary><blockquote>

> ```
> v := x.fromRegex(DATATYPE, yylval, 0)
> ```
Don't use DATATYPE, just use VAR (since VAR is a superset).
Then check if the name is a reserved keyword (in this case, int); Use InSlice to check among multiple keywords/datatypes maybe?
</blockquote></details>

I have called VARNAME now, but have still returned DATATYPE when it catches an 'int'. (I could have returned it as a VARNAME, but that would have made the code extremely non-intuitive.)
___
*[lexer.go, line 80 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuteXx7kHSW24IhG3Z:-LPvGT0FDnZzRlZzScRq:b-co7f31) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L80)):*
<details><summary><i>Previously, cimulator wrote…</i></summary><blockquote>

>```
>, 1)
>```

What is this new flag? Add a comment explaining it.
</blockquote></details>

I have removed it. It was not needed now.

**Review by cimulator — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cimulator/cimulator/16)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @cimulator and @durgeshra)

___
*[lexer.go, line 67 at r1](https://reviewable.io/reviews/cimulator/cimulator/16#-LPuw7o0DgDdow-ScfS6:-LPvOEBg0e9ntlHa1xv9:b4j7bac) ([raw file](https://github.com/cimulator/cimulator/blob/b9d95518e1a97f8b07bb29feefc8a000b8d1c606/lexer.go#L67)):*
<details><summary><i>Previously, durgeshra (Durgesh Agrawal) wrote…</i></summary><blockquote>

I have called VARNAME now, but have still returned DATATYPE when it catches an 'int'. (I could have returned it as a VARNAME, but that would have made the code extremely non-intuitive.)
</blockquote></details>

Yes, this is exactly what I wanted

**Review by cimulator — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cimulator/cimulator/16#-:-LPvOZI05boBLnEd5aLk:bnfp4nl)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @cimulator and @durgeshra)

**Review by cimulator — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cimulator/cimulator/16#-:-LPvOaX89MYQSksyAfVi:b-uwkowd)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @cimulator and @durgeshra)

**Review by cimulator — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cimulator/cimulator/16)* status: all files reviewed, 1 unresolved discussion (waiting on @durgeshra)

**Review by cimulator — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cimulator/cimulator/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
